### ISSUE TITLE
Using Action in Event

### ISSUE THREAD

**Issue by lanhoang712** [microsoft/TextWorld#296]
Hi, how do you define an action such as to create an action-based event? 
I am trying this https://textworld.readthedocs.io/en/stable/textworld.generator.game.html?highlight=event#textworld.generator.game.Event but could not quite figure out how to define an action
For example:
`apple = M.new(type='f', name='apple')`
`eat = Action(name='eat', preconditions=[], postconditions=[M.new_fact("eaten", apple)])`
`event_1 = Event(actions=[eat], commands='eat the apple')`
`q1 = Quest(win_events=[event_1]`
but this produces an error of `AttributeError: 'NoneType' object has no attribute 'items'`

**Comment by MarcCote** [comment]
Hi, correct me if I'm wrong but I believe you want something like this right?
```python
apple = M.new(type='f', name='apple')
apple_eaten_event = Event(conditions={M.new_fact("eaten", apple)})
q1 = Quest(win_events=[apple_eaten_event]
```

If you really wish to define a quest according to an action, you can do the following:
```python
room = M.new("kitchen")
apple = M.new(type='f', name='apple')
room.add(apple)

q1 = M.new_quest_using_commands(["take apple", "eat apple"])
```
or
```python
apple_eaten_event = M.new_event_using_commands(["take apple", "eat apple"])
q1 = Quest(win_events=[apple_eaten_event]
```

Let me know if that's not it. Happy to discuss it more.

**Comment by lanhoang712** [comment]
Perfect, thank you yes that's what I want to do. When would you use the object Action and can it be used for new action?

**Comment by MarcCote** [comment]
Great!

Regarding your follow-up question, under the hood, the `Event` class will look at the last `actions` and use its `postconditions` as the `conditions`. So, your original code is totally fine to create `Event` and `Quest` objects.

However, when building the game, TextWorld tries to infer the text commands from the event's actions. In your case, the `eat` action does not match any rule found in TextWorld's KnowledgeBase.

```python
from textworld.generator import GameMaker, Event, Quest
from textworld.logic import Action

M = GameMaker()
apple = M.new(type='f', name='apple')
eat = Action(name='eat', preconditions=[], postconditions=[M.new_fact("eaten", apple)])
print(eat)
print(M.options.kb.logic.rules['eat'])
```
```bash
eat ::  -> eaten(f_0: f)       # print(eat)
eat :: in(f, I) -> eaten(f)    # print(M.options.kb.logic.rules['eat'])
```
As you can see, your new action is missing the precondition facts to match the existing `eat` rule from the `KnowledgeBase`.

For a completely new action (i.e., that is not already in the KB), you would need to add its `Rule` (i.e., the general form of an action) first. To do so, you will have to add a new `.twl` logic file containing the new rule, any new predicates, and the matching Inform7 code. As an example, you can check the [tw_cooking games](https://github.com/microsoft/TextWorld/tree/master/textworld/challenges/tw_cooking), in particular [meal.twl](https://github.com/microsoft/TextWorld/blob/master/textworld/challenges/tw_cooking/textworld_data/logic/meal.twl#L96-L134).

Since extending TextWorld is far from being user-friendly at the moment, I'm happy to help you out creating new logic if that's something you need.

**Comment by lanhoang712** [comment]
Hi Marc, thank you and sorry for the delay in responding. These examples and the twl file are perfect in explaining how to add actions/rules to the game. Thank you so much! Let me have a play with these and ask you further if I struggle with the new logic :).
